services:

  sgr-mysql:
    image: mysql:9
    environment:
      MYSQL_DATABASE: SGR_DATABASE
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - sgr-data:/var/lib/mysql

  sgr-backend:
    build:
      context: sgr-backend
      dockerfile: Dockerfile
    environment:
      SGR_MYSQL_DB_HOST: sgr-mysql
#      TODO: separa in host e porta
    ports:
      - 8080:8080
    depends_on:
      - sgr-mysql

  sgr-frontend:
    build:
      context: sgr-frontend
      dockerfile: Dockerfile
    environment:
      SGR_BACKEND_API: http://sgr-backend:8080
#      TODO: separa in host e porta
    ports:
      - 3000:3000
    volumes:
      - ./sgr-frontend:/frontend-app
    depends_on:
      - sgr-backend

volumes:
  sgr-data:
